[theme]
backgroundColor = "black"
secondaryBackgroundColor = "indigo"
textColor="lightCyan"
linkColor="darkOrchid"
borderColor = "lightSeaGreen"
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"
baseFontSize = 18
[theme.sidebar]
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"
